# Generated by Django 3.0.6 on 2020-05-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='author_auth_name_23b0c0_idx'),
        ),
    ]
