# Generated by Django 3.0.6 on 2020-05-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200508_1747'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='author_auth_name_23b0c0_idx',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Name'),
        ),
    ]
