# Generated by Django 3.0.6 on 2020-05-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200508_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='author_auth_name_23b0c0_idx'),
        ),
    ]
