# Generated by Django 3.0.6 on 2020-05-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200509_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name'], name='book_book_name_3b5d59_idx'),
        ),
    ]
